# Generated by Django 4.2.4 on 2023-10-20 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_schedules_delete_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedules",
            name="sche_creator",
        ),
    ]
