# Generated by Django 4.2.4 on 2023-10-18 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_student_session_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="relation_ship",
        ),
    ]
