# Generated by Django 4.2.4 on 2023-10-18 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_remove_parent_relation_ship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.student",
            ),
        ),
    ]
