# Generated by Django 4.2.4 on 2023-10-18 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_parent_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="student",
        ),
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.parent",
            ),
        ),
    ]
