# Generated by Django 4.2.4 on 2023-10-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_rename_group_student_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="group",
            new_name="student_group",
        ),
    ]
