# Generated by Django 4.2.4 on 2023-10-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_alter_student_student_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.parent",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.student_group",
            ),
        ),
    ]
