# Generated by Django 4.2.4 on 2023-10-29 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0024_courseallocation_course_length"),
        ("accounts", "0026_alter_student_department_alter_student_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.program",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.parent",
            ),
        ),
    ]
