# Generated by Django 4.2.4 on 2023-10-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_alter_student_department_alter_student_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="student_group",
                to="accounts.student_group",
            ),
        ),
    ]
