# Generated by Django 4.2.4 on 2023-10-13 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0006_courseoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseallocation",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocated_student",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
