# Generated by Django 4.2.4 on 2023-10-15 23:46

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0007_courseallocation_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course_Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_dates",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                        ],
                        null=True,
                        size=None,
                    ),
                ),
                ("repete_times", models.IntegerField(default=0)),
                ("tutor_confirm", models.BooleanField(default=False)),
                ("student_confirm", models.BooleanField(default=False)),
                (
                    "allocations",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_allocation",
                        to="course.courseallocation",
                    ),
                ),
            ],
        ),
    ]
