# Generated by Django 4.2.4 on 2023-10-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0016_alter_course_session_course_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course_session",
            name="course_dates",
        ),
        migrations.AddField(
            model_name="course_session",
            name="select_day",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="course_session",
            name="select_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
