# Generated by Django 4.2.4 on 2023-10-16 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0017_remove_course_session_course_dates_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseallocation",
            name="courses",
        ),
        migrations.AddField(
            model_name="courseallocation",
            name="courses",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocated_course",
                to="course.course",
            ),
            preserve_default=False,
        ),
    ]
