# Generated by Django 4.2.4 on 2023-10-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0020_remove_courseallocation_student_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="courseallocation",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="course_cour_content_cdadd6_idx",
            ),
        ),
    ]
