# Generated by Django 4.2.4 on 2023-10-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0021_courseallocation_course_cour_content_cdadd6_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_session",
            name="start_week_date",
            field=models.DateField(blank=True, max_length=50, null=True),
        ),
    ]
