# Generated by Django 4.2.4 on 2023-10-19 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0022_course_session_start_week_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseallocation",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
