# Generated by Django 4.2.4 on 2023-10-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0024_courseallocation_course_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="credit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("Bachloar", "Bachloar Degree"), ("Master", "Master Degree")],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[("First", "First"), ("Second", "Second"), ("Third", "Third")],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (4, "5"), (4, "6")],
                default=0,
            ),
        ),
    ]
