# Generated by Django 4.2.4 on 2023-10-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0025_alter_course_code_alter_course_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[("First", "First"), ("Second", "Second"), ("Third", "Third")],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="year",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (4, "5"), (4, "6")],
                default=0,
                null=True,
            ),
        ),
    ]
